### ISSUE TITLE
setup AMI build with Packer to run from Gitlab

### ISSUE THREAD

**Issue by ketzacoatl** [ketzacoatl/compute-demo#27]
alt name: write a .gitlab-ci.yml spec to run packer and build an AMI on AWS

NOTE: we have a bunch of prior art and existing code/scripts that can be A) used for guidance and/or B) diced up and reused in some cases. We haven't done this with Gitlab, but with Bamboo, but the majority of what's in the Packer templates path in the TF modules repo is catered to being run by either a CI system or an operator.

**Comment by ketzacoatl** [comment]
Bumping priority on this.

**Comment by kerscher** [comment]
# End-user workflow

1. Change any of the Packer .json specs
1. Commit and push
1. Pipeline is triggered
  1. Lints code
  1. Validates Packer spec
  1. Generates AMI

# Architectural choices and proposed solutions

## Packer needs IAM permissions
### Create IAM user for project, with minimal policy for Packer
- :+1: Permissions only-applicable to project
- :-1: Overhead to create for every new project

### EC2 Instance Profile
- :-1: Allows every pipeline in any project to create AMIs

## Packer spec depends on Terraform output
### Use Same IAM User for Terraform VPC creation, tear down at end
- :+1: Generalizes to any other use of Terraform by CI, constrained by IAM
- :-1: Still need initial separate Terraform run by user to give access 

### Read VPC info directly from State S3 bucket, share across runs
- :+1: Read-only access prevents state corruption
- :-1: Race condition if Terraform is run while pipeline is being executed
- :-1: No guarantees that internal state format will be stable

### Write VPC info to other storage and have pipeline read 
- :+1: Format is guaranteed to be defined and kept by project
- :-1: Data cleanup when project gets archived has to be manually executed

**Comment by kerscher** [comment]
Right now my setup is being written so that:

1. User creates VPC and IAM user with restricted policy only for Packer [minimal permissions](https://www.packer.io/docs/builders/amazon.html#using-an-iam-task-or-instance-role)
1. Script to wrap Terraform writes out to S3 bucket IDs to be used
1. Gitlab has under secret variables location of the bucket to read this from (later can be `vault`)
1. Pipeline uses data from S3 to authenticate with AWS APIs and execute Packer
1. AMI id is written as artifact after `build` stage

**Comment by kerscher** [comment]
Running on `master`.
